# The Bethel Directory — look yourself up by what is wrong.
# Every reference gets machine-verified before it is set.
DIRECTORY = [
("AFRAID", [
 ("When it is dark and you are alone","Psalm 23:4"),
 ("When the news is bad","Psalm 112:7"),
 ("When you have to go first","Joshua 1:9"),
 ("When you are outnumbered","2 Kings 6:16"),
 ("When you cannot sleep for it","Psalm 4:8"),
 ("Before a scan, a flight, a call","Isaiah 41:10"),
 ("When your child is the one afraid","Deuteronomy 31:6"),
 ("Afraid of dying","John 11:25"),
]),
("ANGRY", [
 ("At a person","Ephesians 4:26"),
 ("At God — permitted, and printed","Psalm 13:1"),
 ("At yourself","Psalm 103:8"),
 ("When the anger is fair","James 1:19"),
 ("When you cannot put it down","Romans 12:19"),
 ("Before you answer them","Proverbs 15:1"),
]),
("ANXIOUS", [
 ("General; start here","Philippians 4:6"),
 ("At three in the morning","Psalm 121:3"),
 ("About money","Matthew 6:31"),
 ("About tomorrow specifically","Matthew 6:34"),
 ("When you cannot name it","1 Peter 5:7"),
 ("About your own body","Psalm 139:14"),
]),
("ASHAMED", [
 ("Of something you did","1 John 1:9"),
 ("Of something done to you","Psalm 34:5"),
 ("Of where you are at your age","Joel 2:25"),
 ("When you expect a verdict","Romans 8:1"),
]),
("BETRAYED", [
 ("By a friend","Psalm 55:12"),
 ("By family","Genesis 50:20"),
 ("By a spouse","Psalm 147:3"),
 ("When you still have to see them","Romans 12:18"),
]),
("BROKE", [
 ("When the account is empty","Philippians 4:19"),
 ("When you cannot pay it back","Psalm 40:17"),
 ("When you are ashamed of it","Proverbs 22:2"),
 ("When somebody helps you","2 Corinthians 9:8"),
]),
("BURNED OUT", [
 ("At work","Matthew 11:28"),
 ("At church","1 Kings 19:5"),
 ("On people","Galatians 6:9"),
 ("When resting feels like laziness","Genesis 2:2"),
 ("Jesus tells them to stop","Mark 6:31"),
]),
("BUSY", [
 ("Too busy to pray","Mark 1:35"),
 ("Too busy for people","Luke 10:42"),
 ("When rest feels impossible","Psalm 23:2"),
 ("When the schedule owns you","Ecclesiastes 4:6"),
]),
("CHANGE, FACING", [
 ("A new job","Joshua 1:9"),
 ("A new city","Genesis 12:1"),
 ("A body that changed","Psalm 71:9"),
 ("When you did not want it","Isaiah 43:19"),
]),
("DIVORCED", [
 ("The day it is final","Psalm 34:18"),
 ("When friends pick sides","Psalm 27:10"),
 ("When the kids ask","Psalm 68:5"),
 ("When you feel disqualified","Isaiah 61:3"),
]),
("DOUBTING", [
 ("Whether he is there at all","Psalm 10:1"),
 ("Whether he hears","Psalm 34:15"),
 ("Whether any of it is true","John 20:27"),
 ("Whether you believe enough","Mark 9:24"),
 ("When clever people say no","1 Corinthians 1:18"),
]),
("DYING", [
 ("Somebody you love","1 Thessalonians 4:13"),
 ("Yourself","Psalm 23:4"),
 ("When it is slow","2 Corinthians 4:16"),
 ("What comes after","John 14:2"),
]),
("EMPTY", [
 ("After a big thing ends","1 Kings 19:4"),
 ("When nothing tastes like anything","Ecclesiastes 1:2"),
 ("When you feel nothing at church","Psalm 42:1"),
 ("When you cannot pray","Romans 8:26"),
]),
("FAILED", [
 ("At work","Proverbs 24:16"),
 ("At being good","Romans 7:19"),
 ("Publicly","Psalm 25:2"),
 ("Again","Lamentations 3:22"),
]),
("FORGIVING, TROUBLE", [
 ("When they are not sorry","Luke 23:34"),
 ("When it keeps coming back up","Matthew 18:21"),
 ("When it was your fault","Psalm 51:1"),
 ("When you cannot forgive yourself","1 John 3:20"),
]),
("GRIEVING", [
 ("A person","Psalm 34:18"),
 ("A marriage","Psalm 147:3"),
 ("A pregnancy","Psalm 139:13"),
 ("A parent","2 Samuel 18:33"),
 ("A friendship","Ecclesiastes 3:1"),
 ("When people stop asking","Revelation 21:4"),
 ("Jesus at a funeral","John 11:35"),
]),
("GUILTY", [
 ("For something specific","1 John 1:9"),
 ("For something you cannot name","Romans 8:1"),
 ("For not feeling guilty enough","Psalm 32:1"),
 ("For being fine when others are not","Ecclesiastes 3:4"),
]),
("HOMESICK", [
 ("For a place","Hebrews 11:16"),
 ("For a person","Psalm 42:4"),
 ("For who you used to be","Psalm 51:12"),
 ("For a time that is over","Ecclesiastes 7:10"),
]),
("HOPELESS", [
 ("About a situation","Romans 15:13"),
 ("About a person","Luke 1:37"),
 ("About yourself","Psalm 42:5"),
 ("When you have said it out loud","Psalm 88:1"),
]),
("HUNGRY", [
 ("Actually hungry","Matthew 6:11"),
 ("For something you cannot name","Matthew 5:6"),
 ("When the food ran out","Exodus 16:4"),
 ("Feeding somebody else","Isaiah 58:10"),
]),
("IMPATIENT", [
 ("With God","Psalm 13:1"),
 ("With a person","1 Corinthians 13:4"),
 ("With yourself","Philippians 1:6"),
 ("With how slow it is","2 Peter 3:8"),
]),
("JEALOUS", [
 ("Of somebody's life","Psalm 73:2"),
 ("Of somebody's family","Proverbs 14:30"),
 ("Of somebody at work","Galatians 5:26"),
 ("When they did not earn it","Psalm 37:1"),
]),
("LONELY", [
 ("In a room full of people","Psalm 25:16"),
 ("After moving somewhere new","Genesis 28:15"),
 ("After a breakup","Isaiah 54:5"),
 ("On a Sunday","Hebrews 10:25"),
 ("At night","Psalm 139:12"),
 ("When it has been years","Psalm 68:6"),
]),
("LOST", [
 ("In your own life","Proverbs 3:5"),
 ("Spiritually, and you know it","Luke 15:4"),
 ("In a job you did not choose","Genesis 39:2"),
 ("When you cannot go back","Isaiah 43:18"),
]),
("MARRIAGE, HARD", [
 ("When you are not speaking","Ephesians 4:26"),
 ("When it feels like work","1 Corinthians 13:7"),
 ("When one is trying harder","Colossians 3:13"),
 ("When you need help","Ecclesiastes 4:12"),
]),
("MOVING AWAY", [
 ("Before you go","Genesis 12:1"),
 ("The first night in the new place","Genesis 28:11"),
 ("When you know nobody","Ruth 1:16"),
 ("When it was not your choice","Jeremiah 29:5"),
]),
("NEW AT FAITH", [
 ("Where to start reading","John 1:1"),
 ("What to say","Luke 18:13"),
 ("Whether you must be good first","Romans 5:8"),
 ("Whether you belong yet","Ephesians 2:19"),
]),
("OLD, GETTING", [
 ("When the body slows","Psalm 71:18"),
 ("When you are overlooked","Proverbs 16:31"),
 ("When friends start dying","Psalm 116:15"),
 ("When you wonder if it counted","Psalm 90:12"),
]),
("OVERWHELMED", [
 ("By a list","Luke 10:41"),
 ("By a diagnosis","Psalm 46:1"),
 ("By the news","Psalm 46:10"),
 ("By your own head","Psalm 61:2"),
 ("When you cannot start","Zechariah 4:10"),
]),
("PARENTING", [
 ("A newborn, at 4 a.m.","Psalm 127:2"),
 ("A hard age","Proverbs 22:6"),
 ("One who left","Luke 15:20"),
 ("When you got it wrong","Lamentations 3:22"),
 ("Alone","Psalm 68:5"),
]),
("QUITTING", [
 ("A job","Proverbs 16:9"),
 ("A habit","1 Corinthians 10:13"),
 ("On a person","1 Corinthians 13:7"),
 ("On yourself","Philippians 1:6"),
]),
("REGRET", [
 ("Over a decision","Romans 8:28"),
 ("Over years you cannot get back","Joel 2:25"),
 ("Over a person you hurt","Matthew 5:23"),
 ("When it is too late to fix","Psalm 130:3"),
]),
("RESTLESS", [
 ("Cannot sit still","Psalm 46:10"),
 ("Cannot settle anywhere","Hebrews 13:14"),
 ("Cannot stop scrolling","Psalm 119:37"),
 ("At night","Psalm 63:6"),
]),
("SICK", [
 ("Waiting on results","Psalm 27:14"),
 ("Chronic; no end date","2 Corinthians 12:9"),
 ("Caring for somebody who is","Galatians 6:2"),
 ("When prayer did not fix it","2 Corinthians 12:9"),
]),
("SINGLE", [
 ("And fine with it","1 Corinthians 7:17"),
 ("And not fine with it","Psalm 37:4"),
 ("At a wedding","Psalm 68:6"),
 ("When people ask again","Isaiah 54:1"),
]),
("SORRY", [
 ("To God","Psalm 51:10"),
 ("To a person","Matthew 5:24"),
 ("When you cannot say it","Proverbs 28:13"),
 ("When they will not take it","Romans 12:18"),
]),
("STUCK", [
 ("In a job","Colossians 3:23"),
 ("In a town","Jeremiah 29:7"),
 ("In a season","Ecclesiastes 3:1"),
 ("In the same sin, again","Romans 7:15"),
 ("When nothing at all is moving","Habakkuk 2:3"),
]),
("TEMPTED", [
 ("Generally","1 Corinthians 10:13"),
 ("When you are alone","Psalm 139:7"),
 ("When you already gave in","1 John 2:1"),
 ("When nobody would ever know","Hebrews 4:13"),
]),
("THANKFUL", [
 ("When it is easy","Psalm 100:4"),
 ("When it is not","1 Thessalonians 5:18"),
 ("For a day that went fine","Psalm 118:24"),
 ("For small things","James 1:17"),
]),
("TIRED", [
 ("Physically","Matthew 11:28"),
 ("Of being the strong one","2 Corinthians 12:9"),
 ("Of waiting","Isaiah 40:31"),
 ("Of the same argument","Psalm 55:6"),
 ("Of yourself","Psalm 103:14"),
]),
("TRAPPED", [
 ("In a situation","Psalm 142:7"),
 ("In a body","2 Corinthians 4:16"),
 ("In a pattern","Romans 7:24"),
 ("In somebody else's decision","Genesis 37:28"),
]),
("UNEMPLOYED", [
 ("The first week","Matthew 6:26"),
 ("The sixth month","Habakkuk 3:17"),
 ("When you feel useless","Ephesians 2:10"),
 ("When you finally get one","Colossians 3:23"),
]),
("UNSEEN", [
 ("At work","Colossians 3:24"),
 ("At home","Matthew 6:4"),
 ("By your own family","1 Samuel 16:7"),
 ("She names him: the God who sees","Genesis 16:13"),
]),
("WAITING", [
 ("On an answer","Psalm 27:14"),
 ("On a person to change","2 Peter 3:9"),
 ("On a result","Psalm 62:5"),
 ("On a door to open","Revelation 3:8"),
 ("Longer than you were told","Habakkuk 2:3"),
 ("Twenty years, like Jacob","Genesis 31:41"),
]),
("WEAK", [
 ("Physically","2 Corinthians 12:9"),
 ("In willpower","Matthew 26:41"),
 ("In faith","Mark 9:24"),
 ("When strength is a performance","Isaiah 40:29"),
]),
("WORRIED", [
 ("About your kids","Isaiah 49:15"),
 ("About money","Philippians 4:19"),
 ("About the future","Jeremiah 29:11"),
 ("About somebody far away","Genesis 31:49"),
 ("About what you cannot control","Matthew 6:27"),
]),
("YOUNG", [
 ("When nobody listens to you","1 Timothy 4:12"),
 ("When you feel behind","Ecclesiastes 11:9"),
 ("When adults disappoint you","Psalm 27:10"),
 ("When you are deciding who to be","Proverbs 4:23"),
]),
]
